image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - dev

dev:
    type: deploy
    stage: dev
    image: ruby:latest
    script:
        - cd Fuentes/Servidor/messirveinvertir-be
        - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPMENT --api-key=$HEROKU_API_KEY
    only:
        - dev